# -*- coding: utf-8 -*-
"""day2_session.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFb2KckjYaVgg_P1ojnC5wYJ4nDeU-v0
"""

#import python libraraies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#import csv file
df = pd.read_csv('Diwali Sales Data.csv', encoding='ISO-8859-1')

df.shape

df.head()

df.tail(10)

df.info()

# drop unwanted columns
df.drop(['Status' , 'unnamed1'] ,axis=1, inplace=True)

df.info()

df.head()

pd.isnull(df).sum()

df.dropna(inplace=True)

pd.isnull(df).sum()

df.shape

#change datatype
df['Amount'] = df ['Amount'].astype('int')

df['Amount'].dtypes

df.columns

df.rename(columns={'Marital_Status' : 'Shaadi'})

plt.scatter(x,y)
plt.xlabel("SAT", fontsize = 20)
plt.ylabel("GPA", fontsize = 20)
plt.show()

df.shape

df.nunique

x = df ['Age']
y = df ['Amount']

plt.scatter(x,y)
plt.xlabel("Age group", fontsize = 20)
plt.ylabel("Amount", fontsize = 20)
plt.show()

df.describe()

df[['Age','Amount']].describe()

data_test = [['Joshua',18],['Austin',20],['Aditya', ],['Arjun',19]]
workshop = pd.DataFrame(data_test, columns=['Name','Age'])
workshop

workshop= workshop.dropna()

workshop

x = df['Age']
y = df['Amount']
plt.plot(x,y)
plt.show()

